#include <bits/stdc++.h>
using namespace std;
#define min_3(a,b,c) (min((a),min((b),(c))))
#define all(a) a.begin(),a.end()
#define pb push_back
#define mkp make_pair
#define forn(m,n) for (int i=m; i<n; ++i)
#define fi first
#define se second
#define sz(X) (int)(X).size()

typedef long long ll;
typedef unsigned long long ull;
typedef pair<int,int> pii;
const int mod=1e6+5;
vector<ll>ispr;
ll pr[mod];
//😁😁😁😁😁😁😁😁😁😁😁
void ha(ll n)
{

pr[0]=pr[1]=1;
for(ll i=2;i < mod;++i)
{
    if(!pr[i])
        for(ll j=i*;j<)
}
}
int main()
{

std::ios::sync_with_stdio(false);
cin.tie(0);cout.tie(0);

ha();
return 0;
}





